BAS Platform Extension
SAP/guided-development pull request #9
Opened 2020-09-29 06:38 UTC by perspectivus1

Added a bas-platform extension that exposes an API and interfaces:
    1. Classes for creating actions
    1. Method for executing actions
    1. Method for for obtaining vscode extension APIs

In the future, we'll add more functionality. For example, a message queue for contributor-to-manager communications.

The guided-development extension has an `extensionDepedencies` to the bas-platform extension. It uses it for performing actions.

Each contributing extension also has an `extensionDepedencies` to the bas-platform extension. These extensions use it for creating actions and for obtaining the guided-development extension's API. An example of proper use can be found in the `simple-contrib` sample extension.

The `sample-action-client` extension demonstrates the use of the bas-platform API to perform **scheduled actions**.

2020-09-30 07:20 UTC, perspectivus1 commented on .circleci/config.yml
> +          command: sudo chown -R $(whoami) /usr/local
For `npm link`. We might want to keep performing `npm link` for CI, even once the dependent packages are available on `npm`.

2020-09-30 07:20 UTC, perspectivus1 commented on .circleci/config.yml
> +          command: npm run backend-dev
So we can install, build and link to the dependent `bas-platform` package

2020-09-30 07:20 UTC, perspectivus1 commented on backend/src/extension.ts
> +	const basAPI: typeof bas = await vscode.extensions.getExtension("SAPOSS.bas-platform")?.exports;
Please remind me what the limitation is in Theia regarding case of extension IDs. Would the line above not work in Theia?

2020-09-30 07:20 UTC, perspectivus1 commented on bas-platform/src/api.ts
> +        performAction,
The `bas.actions` object exposes all actions APIs, including classes and methods.

Perhaps all classes should be on the root of the `bas` API hierarchy, similar to the way it's done in `vscode`... @idoprz, what do you think?

2020-09-30 07:23 UTC, tomer-epstein commented on .circleci/config.yml
> +          command: npm run backend-dev
but this is only for development. We don't want/need it in CI.

2020-09-30 07:24 UTC, tomer-epstein commented on .circleci/config.yml
> +          command: sudo chown -R $(whoami) /usr/local
If he dependent packages are available on npm then I don't want to perform any 'npm link'

2020-09-30 07:24 UTC, tomer-epstein commented on backend/src/extension.ts
> +	const basAPI: typeof bas = await vscode.extensions.getExtension("SAPOSS.bas-platform")?.exports;
Would not work in Theia.

2020-09-30 15:20 UTC, tomer-epstein commented on README.md
> +For each of the following folders, perform `npm link @sap-devx/bas-platform` and `npm link @sap-devx/guided-development`:
`npm link bas-platform` and `npm link guided-development`

2020-09-30 16:02 UTC, tomer-epstein commented on README.md
> +For each of the following folders, perform `npm link @sap-devx/bas-platform`:
`npm link bas-platform`

2020-10-02 09:11 UTC, tomer-epstein requested changes
Also we need to update the README. not to perform npm link.

2020-10-02 09:11 UTC, tomer-epstein commented on .circleci/config.yml
> +          command: npm run backend
👍

2020-10-02 09:11 UTC, tomer-epstein commented on backend/package.json
> +		"test2": "nyc mocha -p tsconfig.json --opts ./mocha.opts",
??

2020-10-02 09:11 UTC, tomer-epstein commented on backend/tsconfig.json
> +		"alwaysStrict": true,
"alwaysStrict": true

2020-10-02 09:11 UTC, tomer-epstein commented on backend/tsconfig.json
> +	],
]

2020-10-02 09:11 UTC, tomer-epstein commented on guided-development-types/package.json
> +    "zprepublishOnly": "npm run prep && npm run copy"
why z ?

2020-10-02 09:43 UTC, tomer-epstein commented on README.md
> +For each of the following folders, perform `npm link @sap-devx/bas-platform` and `npm link @sap-devx/guided-development`:
remove, pls.

2020-10-02 09:44 UTC, tomer-epstein commented on README.md
> +For each of the following folders, perform `npm link @sap-devx/bas-platform`:
remove, pls.

2020-10-02 09:50 UTC, tomer-epstein commented on contrib-oven/src/types/GuidedDev.ts
> -}
file should be deleted.

2020-10-02 10:36 UTC, tomer-epstein requested changes

2020-10-02 10:36 UTC, tomer-epstein commented on contrib-oven/src/types/GuidedDev.ts
> -}
file should be deleted.

2020-10-02 11:15 UTC, tomer-epstein approved these changes

2020-10-02 11:21 UTC, merged